import { apiClient } from './apiClient';
import type { ApiResponse, Course } from '@/src/types';

export interface CreateCoursePayload {
  title: string;
  price: number;
  currency?: string;
  free_count?: number;
  description?: string;
  thumbnail?: string;
  status?: 'DRAFT' | 'PUBLISHED' | 'ARCHIVED';
}

export const courseService = {
  /**
   * Create a new course (Instructor/Admin)
  * POST /api/courses
   */
  async createCourse(payload: CreateCoursePayload): Promise<ApiResponse<Course>> {
    return apiClient.post<ApiResponse<Course>>('/api/courses', payload);
  },

  /**
   * Get course details with user access level check
   * GET /api/courses/<course_id>
   */
  async getCourseById(courseId: number | string): Promise<ApiResponse<Course>> {
    return apiClient.get<ApiResponse<Course>>(`/api/courses/${courseId}`);
  },

  /**
   * Get all published courses from API or fallback catalog
   */
  async getExploreCatalog(): Promise<Course[]> {
    try {
      const response = await apiClient.get<ApiResponse>('/api/courses');
      if (response && response.courses && Array.isArray(response.courses) && response.courses.length > 0) {
        return response.courses;
      }
    } catch {
      return [];
    }

    return [];

    return [
      // Top Courses Section
      {
        id: 1,
        title: 'Mastering interaction design: From principles to micro-interactions',
        slug: 'mastering-interaction-design',
        instructor_name: 'Luis Mark',
        instructor_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        price: '$00.00',
        original_price: '$69.00',
        currency: 'USD',
        description: 'Dive into the core principle of interaction design and learn UI workflows.',
        free_count: 3,
        duration: '6hr 20min',
        classes_count: 14,
        rating: 4.9,
        students_count: 1240,
        level: 'Beginner',
        category: 'Product Design',
        status: 'PUBLISHED',
        thumbnail_badge: 'SUMMER EVENTS',
        thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
        tags: ['FREE', 'EVENT', 'BEGINNER'],
        last_updated: '23 May, 2023',
      },
      {
        id: 2,
        title: 'Animate Like a Pro: 3D Motion Graphics & Character Design',
        slug: 'animate-like-a-pro-motion',
        instructor_name: 'Luis Mark',
        instructor_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        price: '$00.00',
        original_price: '$69.00',
        currency: 'USD',
        description: 'Dive into the core principle of motion design and learn 3D animation skills.',
        free_count: 2,
        duration: '9hr 15min',
        classes_count: 22,
        rating: 4.95,
        students_count: 3410,
        level: 'Beginner',
        category: 'Motion Design',
        status: 'PUBLISHED',
        thumbnail_badge: 'POPULAR',
        thumbnail: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=800&auto=format&fit=crop&q=80',
        tags: ['FREE', 'EVENT', 'BEGINNER'],
        last_updated: '18 June, 2023',
      },
      {
        id: 3,
        title: 'Easy Responsive: Modern Web & Cross-Device UI Systems',
        slug: 'easy-responsive-ui-systems',
        instructor_name: 'Luis Mark',
        instructor_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        price: '$00.00',
        original_price: '$69.00',
        currency: 'USD',
        description: 'Dive into the core principle of interaction design and learn adaptive grid mastery.',
        free_count: 4,
        duration: '8hr 39min',
        classes_count: 18,
        rating: 4.88,
        students_count: 2150,
        level: 'Beginner',
        category: 'UI/UX Design',
        status: 'PUBLISHED',
        thumbnail_badge: 'TRENDING',
        thumbnail: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=800&auto=format&fit=crop&q=80',
        tags: ['FREE', 'EVENT', 'BEGINNER'],
        last_updated: '23 May, 2023',
      },
      {
        id: 4,
        title: 'Do This, Not That: UX Architecture & High-Conversion Layouts',
        slug: 'do-this-ux-architecture',
        instructor_name: 'Luis Mark',
        instructor_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        price: '$00.00',
        original_price: '$69.00',
        currency: 'USD',
        description: 'Dive into the core principle of interaction design and learn common UX anti-patterns.',
        free_count: 2,
        duration: '5hr 45min',
        classes_count: 12,
        rating: 4.92,
        students_count: 1890,
        level: 'Beginner',
        category: 'UI/UX Design',
        status: 'PUBLISHED',
        thumbnail_badge: 'EDITOR CHOICE',
        thumbnail: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800&auto=format&fit=crop&q=80',
        tags: ['FREE', 'EVENT', 'BEGINNER'],
        last_updated: '12 July, 2023',
      },

      // All Courses Grid
      {
        id: 5,
        title: 'Become a UX designer in 2024 (Beginner to Professional)',
        slug: 'become-a-ux-designer',
        instructor_name: 'Eichiro D. Lucky',
        instructor_avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
        price: '$52.00',
        original_price: '$62.40',
        discount_percent: '20% Off',
        currency: 'USD',
        description: 'Master end-to-end design thinking, persona creation, wireframing, and user testing.',
        free_count: 3,
        duration: '8hr 39min',
        classes_count: 18,
        rating: 4.9,
        students_count: 4890,
        level: 'Beginner',
        category: 'Product Manager',
        status: 'PUBLISHED',
        thumbnail_badge: 'Free course',
        thumbnail: 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=800&auto=format&fit=crop&q=80',
        last_updated: '23 May, 2023',
      },
      {
        id: 6,
        title: 'Mastering Visual Communication & Viral Content Creation',
        slug: 'mastering-visual-communication',
        instructor_name: 'Eichiro D. Lucky',
        instructor_avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
        price: '$52.00',
        original_price: '$62.40',
        discount_percent: '20% Off',
        currency: 'USD',
        description: 'Create eye-catching visual hooks, thumbnails, and viral brand presentations.',
        free_count: 2,
        duration: '8hr 39min',
        classes_count: 18,
        rating: 4.85,
        students_count: 3200,
        level: 'All Levels',
        category: 'Content Strategy',
        status: 'PUBLISHED',
        thumbnail_badge: 'Free course',
        thumbnail: 'https://images.unsplash.com/photo-1542744094-3a31f272c490?w=800&auto=format&fit=crop&q=80',
        last_updated: '15 June, 2023',
      },
      {
        id: 7,
        title: 'Notion Mastery: Build $15,000 Modular Business Systems',
        slug: 'notion-mastery-business-systems',
        instructor_name: 'Eichiro D. Lucky',
        instructor_avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
        price: '$52.00',
        original_price: '$62.40',
        discount_percent: '20% Off',
        currency: 'USD',
        description: 'Formulate relational databases, project trackers, client portals, and productivity dashboards.',
        free_count: 1,
        duration: '8hr 39min',
        classes_count: 18,
        rating: 4.96,
        students_count: 5120,
        level: 'Intermediate',
        category: 'Productivity',
        status: 'PUBLISHED',
        thumbnail: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=800&auto=format&fit=crop&q=80',
        last_updated: '04 July, 2023',
      },
      {
        id: 8,
        title: 'Shopify E-Commerce Mastery: Must-Have Setup & Store Launch',
        slug: 'shopify-ecommerce-mastery',
        instructor_name: 'Eichiro D. Lucky',
        instructor_avatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=150&auto=format&fit=crop&q=80',
        price: '$52.00',
        original_price: '$62.40',
        discount_percent: '20% Off',
        currency: 'USD',
        description: 'Build high-converting storefronts, configure Payment gateways, and scale drop shipping.',
        free_count: 2,
        duration: '8hr 39min',
        classes_count: 18,
        rating: 4.88,
        students_count: 2740,
        level: 'Beginner',
        category: 'E-Commerce',
        status: 'PUBLISHED',
        thumbnail: 'https://images.unsplash.com/photo-1556742049-0a67c5574f73?w=800&auto=format&fit=crop&q=80',
        last_updated: '29 May, 2023',
      },
      {
        id: 9,
        title: 'Figma to Webflow: Complete Production Pipeline & Animation',
        slug: 'figma-to-webflow-pipeline',
        instructor_name: 'Eichiro D. Lucky',
        instructor_avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
        price: '$52.00',
        original_price: '$62.40',
        discount_percent: '20% Off',
        currency: 'USD',
        description: 'Export designs from Figma into live, lightning-fast, production Webflow websites.',
        free_count: 3,
        duration: '8hr 39min',
        classes_count: 18,
        rating: 4.94,
        students_count: 3890,
        level: 'Advanced',
        category: 'Web Design',
        status: 'PUBLISHED',
        thumbnail_badge: 'Free course',
        thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80',
        last_updated: '11 August, 2023',
      },
      {
        id: 10,
        title: 'Master the Fundamentals of User Experience Design',
        slug: 'master-fundamentals-ux-design',
        instructor_name: 'Eichiro D. Lucky',
        instructor_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        price: '$52.00',
        original_price: '$62.40',
        discount_percent: '20% Off',
        currency: 'USD',
        description: 'Delve into the art and science of creating intuitive, user-centered designs that not only engage but also enhance the overall digital experience.',
        free_count: 3,
        duration: '8hr 39min',
        classes_count: 18,
        rating: 4.97,
        students_count: 6200,
        level: 'Beginner',
        category: 'Product Manager',
        status: 'PUBLISHED',
        thumbnail: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=800&auto=format&fit=crop&q=80',
        last_updated: '23 May, 2023',
      },
      {
        id: 11,
        title: 'Adobe Illustrator Vector Art & Logo Branding Blueprint',
        slug: 'adobe-illustrator-vector-art',
        instructor_name: 'Eichiro D. Lucky',
        instructor_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        price: '$52.00',
        original_price: '$62.40',
        discount_percent: '20% Off',
        currency: 'USD',
        description: 'Master the pen tool, Bézier curves, isometric grids, and vector packaging art.',
        free_count: 2,
        duration: '8hr 39min',
        classes_count: 18,
        rating: 4.9,
        students_count: 2190,
        level: 'Intermediate',
        category: 'Graphic Design',
        status: 'PUBLISHED',
        thumbnail: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800&auto=format&fit=crop&q=80',
        last_updated: '01 June, 2023',
      },
      {
        id: 12,
        title: 'Photoshop for Creative Pros: Color Grading & Photo Manipulation',
        slug: 'photoshop-creative-pros',
        instructor_name: 'Eichiro D. Lucky',
        instructor_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        price: '$52.00',
        original_price: '$62.40',
        discount_percent: '20% Off',
        currency: 'USD',
        description: 'Advanced retouching, luminance masking, composite lighting, and high-end aesthetics.',
        free_count: 2,
        duration: '8hr 39min',
        classes_count: 18,
        rating: 4.91,
        students_count: 3410,
        level: 'Beginner',
        category: 'Graphic Design',
        status: 'PUBLISHED',
        thumbnail: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80',
        last_updated: '14 May, 2023',
      },
    ];
  },
};

